### ISSUE TITLE
Secure Build level 1

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#120]
Rewrite Secure Build level 1 to make sure that it's about a defined process, rather than to expecting that there's a separate (Word-like) document that describes it. If an organization would have an automated build system, it would also be defined ...

**Comment by itscooper** [comment]
I agree - this activity was originally written with this in mind, but it has been through numerous iterations since then. But the idea that this does not have to literally be a word-processed document is correct so if it doesn't read that way I agree it needs changing.

When you say 'rewrite', I'm assuming you don't mean from scratch? 

I'll have a crack at modifying the existing content as I think that's all that's needed IMO.

**Comment by itscooper** [comment]
How's this: b4f2819b086e4ee7085f3ce8cc740d8b778b74a4 ?

**Comment by SebaDele** [comment]
done
