### ISSUE TITLE
review i-secure-build

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#42]
secrets management - make clear that this is for the build stage (there is a secrets mgmt stream as part of the deploy stage later on)

consider including security testing tools already in maturity level 1?

typo:
Ideally, handle code singing = signing

L3
consider "defect acted upon within SLA" instead of breaking the build
add "filter" to not break the build afterwards when treating/accepting the defect
not only static testing?
expand "custom ruleset" more? regression checking with rules as part of the static testing.

**Comment by itscooper** [comment]
Most fixed in #095b177

> consider "defect acted upon within SLA" instead of breaking the build

I've thought about this, and personally I feel that there should always be a threshold of risk that breaks the build in a maturity 3 organisation/team. I.e. the risk is high enough that the build output would be unsafe to run under normal circumstances. However, I appreciate that technical limitations could be an issue. I've therefore added an alternative to breaking the build here: #c87ac66

> not only static testing?

As discussed on the call, I personally can't think of any other types of testing that would work at build-time, since you can't do DAST etc at all until after the build. However, if anyone can think of some other types I'll happily add them in.

> expand "custom ruleset" more? regression checking with rules as part of the static testing.

Regression checking is already mentioned, as are rules based on the threat model. I couldn't think of any further decent examples, but happy to add any in that others can think of.

**Comment by itscooper** [comment]
Review activity stream B against o-environment-management - they should be similar.
