### ISSUE TITLE
Distribution and automation of patches for software being developed

### ISSUE THREAD

**Issue by itscooper** [OWASP/samm#51]
Where does this fit? How to distribute your own patches to customers. Do you force them?

**Comment by 23bartman** [comment]
IMO this should go under Environment Management, stream B: Patching and Updating. but it's currently not described there. Do you agree ?

**Comment by dkefer** [comment]
If I understand the query correctly, I'm not quite sure this belongs in the model, given the implicit separation of responsibilities between a vendor and a customer. 

IMHO as a customer, I'm responsible for patching of software provided by my vendor entirely myself. If it's otherwise, it's probably rather vendor's business decision than sign of particular maturity. 

Maybe I'm overseeing sth? An example might help.

**Comment by SebaDele** [comment]
covered in #53
