### ISSUE TITLE
Why questions in Assessment Toolbox and OWASP SAMM v2.0 are different?

### ISSUE THREAD

**Issue by Shkarbatov** [OWASP/samm#572]
Why questions in [SAMM_Assessment_Toolbox_v2.0-WIP.xlsx](https://github.com/OWASP/samm/blob/master/SAMM_Assessment_Toolbox_v2.0-WIP.xlsx) and [OWASP-SAMM-v2.0.pdf](https://github.com/OWASP/samm/blob/master/Supporting%20Resources/v2.0/OWASP-SAMM-v2.0.pdf) are different?

**Comment by 23bartman** [comment]
Hi Shkarbatov. Thanks for your question. There are two things that could be causing this:
1. Since version 2.0 of OpenSAMM, we want to support faster updates to the model. See also this blogpost: https://owaspsamm.org/blog/2021/03/23/samm-suite/. The website is currently showing the latest minor version of the model, which might differ from SAMM 2.0 and the assessment toolbox (which are still aligned). With our new versioning system, we will be able to implement necessary changes faster, and we're using a semantic versioning model for this. It is the idea that website and toolbox are always aligned (when you're using the same version), the fact that they differ is just a temporary situation. Sorry for that.
2. we're in the middle of transferring between Github repo's. This might also lead to some (temporary) glitches. 

Kind regards,
Bart.
