### ISSUE TITLE
Create PDF from markup

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#70]
To be tested/created for SAMMv2 (first with beta)
Here is the process https://github.com/OWASP/OWASP-Books/tree/master/TemplateBook
Basically it a combination of pandoc and make

**Comment by nessimk** [comment]
I spent a couple of hours exploring the feasibility of this approach before we released the beta. While I did manage to generate a PDF , it's not usable without a major reorganisation of the text that's currently on github which is something we'd rather avoid given that it's driving the live website which makes it subject to certain Hugo constraints.

**Here are my observations:**
Pandoc treats each markdown level 1 heading as a chapter, which is a problem for us as all source files in github start with level 1 headings (#short description, #long description, ...). So, to get the text to render meaningfully, we'd have to demote those and have a single level 1 heading per business function (presumably the name of the function). 

I concatenated each business function's activities into 1 file to create 1 chapter per business function when generating my trial PDF.  The problem here is that we'll end up with the SAMM content spread across multiple layouts (what's currently in github driving the website and whatever we reformat for the purposes of generating the PDF).

A better approach would be to automatically generate the markdown input for the PDF from the currently available files in github. This should be feasible, especially as the current file layout is standardised and backed by a data model.

I would avoid doing it with smple bash/sed scripts that are agnostic about markdown semantics, but I don't know any specialised tools for this and a quick google did not enlighten me.

**Some practical details:**
Note that the Makefile referenced in the instructions doesn't preserve the order of the files (i.e. 01-intro.md 02-chapter1.md 03-chapter2.md..) when it passes them to pandoc. Your resulting book won't be properly ordered. I didn't have time to look into it and instead just manually overrode the command.

Pandoc goes via Latex for markdown to pdf conversion which is not particularly friendly for people not familiar with latex.  If anyone needs it, [here's](https://gist.github.com/nessimk/c13839f89552f9968734ff24ac64be96) the debug output of my pandoc command showing all the latex packages required for a successful run.

As a final remark, if we want any pictures in the PDF we need the source files. I took a screenshot of the SAMM v1.5 book's cover page as i couldn't find it anywhere online...and it was promptly ignored by pandoc, so that's something else to look into.

**Comment by fzipi** [comment]
This is all based on a latex template. I can give the team some tips on getting a better version.

**Comment by nessimk** [comment]
Created a [pdf](https://github.com/OWASP/samm/blob/nk-basic-pdf-from-object-model/Supporting%20Resources/v2.0/OWASP-SAMM2.pdf) from the content in the yaml model files using a simple mustache-like template and some python processing.

The pdf and the process are currently in the [nk-basic-pdf-from-object-model](https://github.com/OWASP/samm/tree/nk-basic-pdf-from-object-model) branch in the [Supporting Resources](https://github.com/OWASP/samm/tree/nk-basic-pdf-from-object-model/Supporting%20Resources/v2.0) See the [README](https://github.com/OWASP/samm/blob/nk-basic-pdf-from-object-model/Supporting%20Resources/v2.0/building-the-pdf/README).
