### ISSUE TITLE
Terminology (by Altaz Valani via Slack)

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#91]
Beta feedback: I come from a world where guidance needs to be auditable. Suggest collapsing activities into crisp bullets of actionable “shall” and “should” statements”, ideally with an eye toward increasing automation while still remaining tool agnostic. Also, it seems we are recommending artifacts without being explicit (ex. “..interview business owners and stakeholders and document drivers..“). I would push the example by asking, “Is email documentation therefore a good enough software security practice?“. (edited)

**Comment by Pat-Duarte** [comment]
To ensure auditability: 
1. Convert activities into “shall” (mandatory) and “should” (nice to have) statements. 
2. Clearly identify what artifacts need to be produced.
Any auditor looking at this should have a clear reference point (we should try and help remove subjectivity in this). Hence the “shall” and “should” statements. 

Be explicit about output artifacts.
In terms of the artifacts, it will help accelerate the right governance otherwise teams we may see a wide range of outputs with varying quality all claiming to be “SAMM 2.0 compliant”.

**Comment by SebaDele** [comment]
it is not the primary purpose of SAMM to become an audit baseline. based on the model, the questions and quality criteria someone can create this.
